# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-03 15:53
from __future__ import unicode_literals

import django.db.models.deletion
import morango.models.fields.uuids
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0030_contentnode_ancestors"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentNodeExtras",
            fields=[
                (
                    "content_node",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="content.ContentNode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalContentTag",
            fields=[
                (
                    "id",
                    morango.models.fields.uuids.UUIDField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("tag_name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="contentnodeextras",
            name="tags",
            field=models.ManyToManyField(
                related_name="tagged_content",
                to="kolibri_explore_plugin.ExternalContentTag",
            ),
        ),
    ]
