# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-27 20:46
from __future__ import unicode_literals

import django.db.models.deletion
import morango.models.fields.uuids
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0030_contentnode_ancestors"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalContentTag",
            fields=[
                (
                    "id",
                    morango.models.fields.uuids.UUIDField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("tag_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TaggedContent",
            fields=[
                (
                    "content_node",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="content.ContentNode",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="tagged_content",
                        to="kolibri_explore_plugin.ExternalContentTag",
                    ),
                ),
            ],
        ),
    ]
